import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getAuthenticatedAppForUser } from "@/serverApp";
import { AuthProvider } from "@/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { user } = getAuthenticatedAppForUser();
  return (
    <html lang="en">
      <AuthProvider initialUser={user}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
